spring.application.name=SpringAiQuickStart

server.port=8081

spring.ai.deepseek.api-key=sk-ce83d8b9f6464092a4734dd5072672e7
spring.ai.deepseek.chat.options.model=deepseek-chat

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8

