spring.application.name=SpringAiQuickStart
spring.config.import=optional:classpath:application-local.properties

server.port=8081

spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY:}
spring.ai.deepseek.chat.options.model=deepseek-chat

spring.ai.zhipuai.api-key=${ZHIPUAI_API_KEY:}
spring.ai.zhipuai.embedding.options.model=embedding-2

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8

